[build]
  command = "npm run build:client"
  publish = "dist/spa"
  environment = { NODE_VERSION = "20" }

[[redirects]]
  from = "/api/*"
  to = "https://51be3d6708344836a6f6586ec48b1e4b-476bca083d854b2a92cc8cfa4.fly.dev/api/:splat"
  status = 200
  force = true
